import Head from 'next/head';
import Image from 'next/image';
import styles from './Home.module.css';
import Header from '../../components/layout/Header/Header';
import Main from '../../components/layout/Main/Main';
import Form from '../../components/ui/Form/Form';

const formFields = [
  { name: 'name', initialValue: '', type: 'text' },
  { name: 'category', initialValue: '', type: 'text' },
  { name: 'price', initialValue: 0, type: 'number' },
];

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Main>
        <Form fields={formFields} />
      </Main>
      <footer className={styles.footer}></footer>
    </div>
  );
}
